# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enables parallel compilation
org.gradle.parallel=true

# Enables caching of build outputs
org.gradle.caching=true

# Enables configuration on demand
org.gradle.configureondemand=true

# Disables configuration caching to avoid JdkImageTransform issues
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
